routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
     return view('home');
});    

Route::get('login','Admin_controller@view_login')->name('view_login');	
Route::post('process_login','Admin_controller@process_login')->name('process_login');
Route::group(['prefix'=>'admin', 'as'=>'admin.','middleware' => [ 'CheckLogin' ] ], function () {

	Route::get('infor','Admin_controller@infor')->name('infor');
    Route::get('admin_editor/{ma_admin}','Admin_controller@admin_editor')->name('admin_editor');
	Route::post('admin_editor/{ma_admin}','Admin_controller@handle')->name('handle');
	
//benhnhan
	Route::get('patients','Patient_controller@view')->name('patients');



// doctor

   Route::get('doctors','doctor_controller@doctors')->name('doctors');

   Route::get('add_doctor','doctor_controller@add_doctor')->name('add_doctor');

   Route::post('process_add_doctor','doctor_controller@process_add_doctor')->name('process_add_doctor');

   Route::get('view_update_doctor/{ma_bac_si}','doctor_controller@view_update_doctor')->name('view_update_doctor');

   Route::post('process_update_doctor/{ma_bac_si}','doctor_controller@process_update_doctor')->name('process_update_doctor');

   Route::get('delete_doctor/{ma_bac_si}','doctor_controller@delete_doctor')->name('delete_doctor');


   

 // Route::get('xoa_admin/{ma_admin}','Admin_controller@xoa_admin')->name('admin.xoa_admin');

	 // Route::get('them_admin','Admin_controller@them_admin')->name('them_admin');
  //    Route::post('them_admin','Admin_controller@them_xu_ly')->name('admin.them_xu_ly');

	// Route::get('them_benh_nhan','benh_nhan_controller@them_benh_nhan')->name('them_benh_nhan');
	// Route::post('them_benh_nhan','benh_nhan_controller@them_xu_ly')->name('benh_nhan.them_xu_ly');

	// Route::get('sua_benh_nhan/{ma_benh_nhan}','benh_nhan_controller@sua_benh_nhan')->name('benh_nhan.sua_benh_nhan');
	// Route::post('sua_benh_nhan/{ma_benh_nhan}','benh_nhan_controller@sua_xu_ly')->name('benh_nhan.sua_xu_ly');

	 

});












 

resources/views/Bacsi/add_doctor.blade.php
@extends('admin.layout')
@section('view')

<style>
.card {d
  position: absolute;
  right: -500px;
  width: 300px;
  border: 3px solid #73AD21;
  padding: 10px;
}
</style>

<div class="content">
	<div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-6 col-md-12">
                            <div class="card">
                            	<div class="card-content table-responsive">
                                    <table class="table table-hover">


									<form method="post" method="post" action="{{route('#',['ma_bac_si'=>$i])}}">
										<input type="hidden" name="_token" value="{{csrf_token()}}">
										@foreach ($info as $each)
										ma_bac_si:<input type="number" name="ma" value="{{$each->ma_bac_si}}"><br>
										ten:<input type="text" name="ten_admin" value="{{$each->ten}}"><br>
										email:<input type="text" name="email" value="{{$each->email}}"><br>
										mat_khau:<input type="text" name="mat_khau" value="{{$each->mat_khau}}"><br>
										@endforeach
									   
									</form>
								</table>
							</div>
							</div>
						</div>
					</div>
	</div>
</div>

resources/views/Bacsi/doctor.blade.php
@extends('admin.layout')
@section('view')

<style>
.card {d
  position: absolute;
  right: -500px;
  width: 300px;
  border: 3px solid #73AD21;
  padding: 10px;
}
</style>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-icon" data-background-color="purple">
                <i class="material-icons">assignment</i>
            </div>
            <div class="card-content">
                <h4 class="card-title">DataTables.net</h4>
                <div class="toolbar">
                	<a href="{{route('admin.add_doctor')}}">Them</a>
                </div>
                <div class="material-datatables">
                    <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>PhoneNumber</th>
                                <th class="disabled-sorting text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        	@foreach ($result as $each)
                            <tr>
                                <td>{{$each->ma_bac_si}}</td>
                                <td>{{$each->ten}}</td>
                                <td>{{$each->email}}</td>
                                <td>{{$each->sdt}}</td>
                                <td class="text-right">
                                    <a href="#" class="btn btn-simple btn-info btn-icon like"><i class="material-icons">favorite</i></a>
                                    <a href="#" class="btn btn-simple btn-warning btn-icon edit"><i class="material-icons">dvr</i></a>
                                    <a href="#" class="btn btn-simple btn-danger btn-icon remove"><i class="material-icons">close</i></a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- end content-->
        </div>
        <!--  end card  -->
    </div>
    <!-- end col-md-12 -->
</div>
@endsection
@push('js')
<script type="text/javascript">
    $(document).ready(function() {
        $('#datatables').DataTable({
            "pagingType": "full_numbers",
            "lengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "All"]
            ],
            responsive: true,
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search records",
            }

        });


    //     var table = $('#datatables').DataTable();

    //     // Edit record
    //     table.on('click', '.edit', function() {
    //         $tr = $(this).closest('tr');

    //         var data = table.row($tr).data();
    //         alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
    //     });

    //     // Delete a record
    //     table.on('click', '.remove', function(e) {
    //         $tr = $(this).closest('tr');
    //         table.row($tr).remove().draw();
    //         e.preventDefault();
    //     });

    //     //Like record
    //     table.on('click', '.like', function() {
    //         alert('You clicked on Like button');
    //     });

    //     $('.card .material-datatables label').addClass('form-group');
    });
	
</script>
@endpush